




[platformio]
default_envs = uno_pedals

[env:leonardo]
platform = atmelavr
board = leonardo
framework = arduino
build_src_filter = +<wheels/>
upload_port = COM14
monitor_port = COM14
monitor_speed = 250000

[env:uno_pedals]
platform = atmelavr
board = uno
framework = arduino
build_src_filter = +<pedals/>
upload_port = COM6
monitor_port = COM6
monitor_speed = 115200

[env:uno_controlpanel]
platform = atmelavr
board = uno
framework = arduino
build_src_filter = +<uno_controlpanel/>
upload_port = COM8
monitor_port = COM8
monitor_speed = 115200


